CREATE OR REPLACE TABLE `tableautb.tb_analysis.tb_cleaned` AS
SELECT
  `Country or territory name` AS country,
  'ISO 2-character country_territory code' AS iso_2_character_country_code,
  'ISO 3-character country_territory code' AS iso_3_character_country_code,
  'ISO numeric country_territory code' AS iso_numeric_country_code,
  `Region` AS region,
  `Year` AS year,
  `Estimated total population number` AS population,
  'Estimated prevalence of TB _all forms_ per 100 000 population' AS tb_prevalence_per_100k,
  'Estimated prevalence of TB _all forms_ per 100 000 population_ low bound' AS tb_prevalence_per_100k_lowbound,
  'Estimated prevalence of TB _all forms_ per 100 000 population_ high bound' AS tb_prevalence_per_100k_highbound,
  'Estimated prevalence of TB _all forms_' AS tb_prevalence,
  'Estimated prevalence of TB _all forms__ low bound' AS tb_prevalence_lowbound,
  'Estimated prevalence of TB _all forms__ high bound' AS tb_prevalence_highbound,
  'Method to derive prevalence estimates' AS prevalence_method,
  'Estimated mortality of TB cases _all forms_ excluding HIV_ per 100 000 population' AS tb_mortality_exclude_HIV_per_100k,
  'Estimated mortality of TB cases _all forms_ excluding HIV__ per 100 000 population_ low bound' AS tb_mortality_exclude_HIV_per_100k_lowbound,
  'Estimated mortality of TB cases _all forms_ excluding HIV__ per 100 000 population_ high bound' AS tb_mortality_exclude_HIV_per_100k_highbound,
  'Estimated number of deaths from TB _all forms_ excluding HIV_' AS tb_death_exdlude_HIV,
  'Estimated number of deaths from TB _all forms_ excluding HIV__ low bound' AS tb_death_exdlude_HIV_lowbound,
  'Estimated number of deaths from TB _all forms_ excluding HIV__ high bound' AS tb_death_exdlude_HIV_highbound,
  'Estimated mortality of TB cases who are HIV-positive_ per 100 000 population' AS tb_mortality_HIV_per_100k,
  'Estimated mortality of TB cases who are HIV-positive_ per 100 000 population_ low bound' AS tb_mortality_HIV_per_100k_lowbound,
  'Estimated mortality of TB cases who are HIV-positive_ per 100 000 population_ high bound' AS tb_mortality_HIV_per_100k_highbound,
  'Estimated number of deaths from TB in people who are HIV-positive' AS tb_death_HIV,
  'Estimated number of deaths from TB in people who are HIV-positive_ low bound' AS tb_death_HIV_lowbound,
  'Estimated number of deaths from TB in people who are HIV-positive_ high bound' AS tb_death_HIV_highbound,
  'Method to derive mortality estimates' AS mortality_method,
  `Estimated incidence _all forms_ per 100 000 population` AS tb_incidence_per_100k,
  'Estimated incidence _all forms_ per 100 000 population_ low bound' AS tb_incidence_per_100k_lowbound,
  'Estimated incidence _all forms_ per 100 000 population_ high bound' AS tb_incidence_per_100k_highbound,
  'Estimated number of incident cases _all forms_' AS tb_incident_cases,
  'Estimated number of incident cases _all forms__ low bound' AS tb_incident_cases_lowbound,
  'Estimated number of incident cases _all forms__ high bound' AS tb_incident_cases_highbound,
  'Method to derive incidence estimates' AS incidence_method,
  'Estimated HIV in incident TB _percent_' AS tb_HIV_incident_percent,
  'Estimated HIV in incident TB _percent__ low bound' AS tb_HIV_incident_percent_lowbound,
  'Estimated HIV in incident TB _percent__ high bound' AS tb_HIV_incident_percent_highbound,
  'Estimated incidence of TB cases who are HIV-positive per 100 000 population' AS tb_incidence_HIV_per_100k,
  'Estimated incidence of TB cases who are HIV-positive per 100 000 population_ low bound' AS tb_incidence_HIV_per_100k_lowbound,
  'Estimated incidence of TB cases who are HIV-positive per 100 000 population_ high bound' AS tb_incidence_HIV_per_100k_highbound,
  'Estimated incidence of TB cases who are HIV-positive' AS tb_incidence_HIV,
  'Estimated incidence of TB cases who are HIV-positive_ low bound' AS tb_incidence_HIV_lowbound,
  'Estimated incidence of TB cases who are HIV-positive_ high bound' AS tb_incidence_HIV_highbound,
  'Method to derive TBHIV estimates' AS TBHIV_method,
  'Case detection rate _all forms__ percent' AS tb_case_detection_rate,
  'Case detection rate _all forms__ percent_ low bound' AS tb_case_detection_rate_lowbound,
  'Case detection rate _all forms__ percent_ high bound' AS tb_case_detection_rate_highbound

FROM `tableautb.tb_analysis.raw_tb_dataset`;
